In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from imblearn.over_sampling import SMOTE

In [2]:
column_names = [
    "age",
    "sex",
    "height",
    "weight",
    "qrsduration",
    "printerval",
    "qtinterval",
    "tinterval",
    "pinterval",
    "qrs",
    "t",
    "p",
    "qrst",
    "j",
    "heartrate",
]

for i in ["q", "r", "s", "r1", "s1"]:
    column_names.append("di_"+i)

column_names.append("num_intrisic_deflections")

column_names.append("ragged_r")
column_names.append("diphasic_r")

column_names.append("ragged_p")
column_names.append("diphasic_p")

column_names.append("ragged_t")
column_names.append("diphasic_t")

for i in range(28, 280):
    column_names.append(f"channel_{i}")

column_names.append('target')

In [3]:
data = pd.read_csv('../data/arrhythmia/arrhythmia.data', header=None, names=column_names)

In [4]:
data.head()

,age,sex,height,weight,qrsduration,printerval,qtinterval,tinterval,pinterval,qrs,...,channel_271,channel_272,channel_273,channel_274,channel_275,channel_276,channel_277,channel_278,channel_279,target
0,75,0,190,80,91,193,371,174,121,-16,...,0.0,9.0,-0.9,0.0,0.0,0.9,2.9,23.3,49.4,8
1,56,1,165,64,81,174,401,149,39,25,...,0.0,8.5,0.0,0.0,0.0,0.2,2.1,20.4,38.8,6
2,54,0,172,95,138,163,386,185,102,96,...,0.0,9.5,-2.4,0.0,0.0,0.3,3.4,12.3,49.0,10
3,55,0,175,94,100,202,380,179,143,28,...,0.0,12.2,-2.2,0.0,0.0,0.4,2.6,34.6,61.6,1
4,75,0,190,80,88,181,360,177,103,-16,...,0.0,13.1,-3.6,0.0,0.0,-0.1,3.9,25.4,62.8,7

In [5]:
data = data.drop(["j"], axis=1)

In [6]:
data.head()

,age,sex,height,weight,qrsduration,printerval,qtinterval,tinterval,pinterval,qrs,...,channel_271,channel_272,channel_273,channel_274,channel_275,channel_276,channel_277,channel_278,channel_279,target
0,75,0,190,80,91,193,371,174,121,-16,...,0.0,9.0,-0.9,0.0,0.0,0.9,2.9,23.3,49.4,8
1,56,1,165,64,81,174,401,149,39,25,...,0.0,8.5,0.0,0.0,0.0,0.2,2.1,20.4,38.8,6
2,54,0,172,95,138,163,386,185,102,96,...,0.0,9.5,-2.4,0.0,0.0,0.3,3.4,12.3,49.0,10
3,55,0,175,94,100,202,380,179,143,28,...,0.0,12.2,-2.2,0.0,0.0,0.4,2.6,34.6,61.6,1
4,75,0,190,80,88,181,360,177,103,-16,...,0.0,13.1,-3.6,0.0,0.0,-0.1,3.9,25.4,62.8,7

In [7]:
len(data.index)

452

In [8]:
data = data.replace("?", np.nan)

In [9]:
data = data.dropna()

In [10]:
len(data.index)

420

In [11]:
data["sex"].value_counts()

sex
1    235
0    185
Name: count, dtype: int64

In [12]:
len(data[(data['age'] >= 45) & (data['age'] <= 65)])

179

In [13]:
data['age'] = ((data['age'] < 45) | (data['age'] > 65)).astype(int) # not middle aged

In [14]:
len(data[data["age"] == 0].index)

179

In [15]:
data.head()

,age,sex,height,weight,qrsduration,printerval,qtinterval,tinterval,pinterval,qrs,...,channel_271,channel_272,channel_273,channel_274,channel_275,channel_276,channel_277,channel_278,channel_279,target
0,1,0,190,80,91,193,371,174,121,-16,...,0.0,9.0,-0.9,0.0,0.0,0.9,2.9,23.3,49.4,8
1,0,1,165,64,81,174,401,149,39,25,...,0.0,8.5,0.0,0.0,0.0,0.2,2.1,20.4,38.8,6
2,0,0,172,95,138,163,386,185,102,96,...,0.0,9.5,-2.4,0.0,0.0,0.3,3.4,12.3,49.0,10
3,0,0,175,94,100,202,380,179,143,28,...,0.0,12.2,-2.2,0.0,0.0,0.4,2.6,34.6,61.6,1
5,1,0,169,51,100,167,321,174,91,107,...,-0.6,12.2,-2.8,0.0,0.0,0.9,2.2,13.5,31.1,14

In [16]:
len(data[data["target"] == 1])

237

In [17]:
len(data[data["target"] != 1])

183

In [18]:
data['target'] = (data['target'] == 1).astype(int) # not middle aged

In [19]:
len(data[data["target"] == 1])

237

In [20]:
len(data[data["target"] == 0])

183

In [21]:
data.head()

,age,sex,height,weight,qrsduration,printerval,qtinterval,tinterval,pinterval,qrs,...,channel_271,channel_272,channel_273,channel_274,channel_275,channel_276,channel_277,channel_278,channel_279,target
0,1,0,190,80,91,193,371,174,121,-16,...,0.0,9.0,-0.9,0.0,0.0,0.9,2.9,23.3,49.4,0
1,0,1,165,64,81,174,401,149,39,25,...,0.0,8.5,0.0,0.0,0.0,0.2,2.1,20.4,38.8,0
2,0,0,172,95,138,163,386,185,102,96,...,0.0,9.5,-2.4,0.0,0.0,0.3,3.4,12.3,49.0,0
3,0,0,175,94,100,202,380,179,143,28,...,0.0,12.2,-2.2,0.0,0.0,0.4,2.6,34.6,61.6,1
5,1,0,169,51,100,167,321,174,91,107,...,-0.6,12.2,-2.8,0.0,0.0,0.9,2.2,13.5,31.1,0

In [22]:
data["target"].value_counts()

target
1    237
0    183
Name: count, dtype: int64

In [23]:
columns = data.columns

In [24]:
x, y = data.iloc[:, :-1], data.iloc[:, -1]
y.reset_index()
scaler = MinMaxScaler()
scaler.fit(x)
x_transf = scaler.transform(x)

In [25]:
data = pd.DataFrame(x_transf, columns=x.columns, index=x.index)

In [26]:
data.head()

,age,sex,height,weight,qrsduration,printerval,qtinterval,tinterval,pinterval,qrs,...,channel_270,channel_271,channel_272,channel_273,channel_274,channel_275,channel_276,channel_277,channel_278,channel_279
0,1.0,0.0,0.125926,0.435294,0.270677,0.368321,0.501805,0.233333,0.590244,0.457478,...,0.638554,1.000000,0.381356,0.968531,0.0,0.0,0.53125,0.741667,0.507519,0.569579
1,0.0,1.0,0.088889,0.341176,0.195489,0.332061,0.610108,0.140741,0.190244,0.577713,...,0.614458,1.000000,0.360169,1.000000,0.0,0.0,0.31250,0.675000,0.485714,0.500971
2,0.0,0.0,0.099259,0.523529,0.624060,0.311069,0.555957,0.274074,0.497561,0.785924,...,0.783133,1.000000,0.402542,0.916084,0.0,0.0,0.34375,0.783333,0.424812,0.566990
3,0.0,0.0,0.103704,0.517647,0.338346,0.385496,0.534296,0.251852,0.697561,0.586510,...,0.686747,1.000000,0.516949,0.923077,0.0,0.0,0.37500,0.716667,0.592481,0.648544
5,1.0,0.0,0.094815,0.264706,0.338346,0.318702,0.321300,0.233333,0.443902,0.818182,...,0.674699,0.853659,0.516949,0.902098,0.0,0.0,0.53125,0.683333,0.433835,0.451133

In [27]:
data.index

Index([  0,   1,   2,   3,   5,   6,   7,   8,   9,  10,
       ...
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451],
      dtype='int64', length=420)

In [28]:
data["target"] = y

In [29]:
data.head()

,age,sex,height,weight,qrsduration,printerval,qtinterval,tinterval,pinterval,qrs,...,channel_271,channel_272,channel_273,channel_274,channel_275,channel_276,channel_277,channel_278,channel_279,target
0,1.0,0.0,0.125926,0.435294,0.270677,0.368321,0.501805,0.233333,0.590244,0.457478,...,1.000000,0.381356,0.968531,0.0,0.0,0.53125,0.741667,0.507519,0.569579,0
1,0.0,1.0,0.088889,0.341176,0.195489,0.332061,0.610108,0.140741,0.190244,0.577713,...,1.000000,0.360169,1.000000,0.0,0.0,0.31250,0.675000,0.485714,0.500971,0
2,0.0,0.0,0.099259,0.523529,0.624060,0.311069,0.555957,0.274074,0.497561,0.785924,...,1.000000,0.402542,0.916084,0.0,0.0,0.34375,0.783333,0.424812,0.566990,0
3,0.0,0.0,0.103704,0.517647,0.338346,0.385496,0.534296,0.251852,0.697561,0.586510,...,1.000000,0.516949,0.923077,0.0,0.0,0.37500,0.716667,0.592481,0.648544,1
5,1.0,0.0,0.094815,0.264706,0.338346,0.318702,0.321300,0.233333,0.443902,0.818182,...,0.853659,0.516949,0.902098,0.0,0.0,0.53125,0.683333,0.433835,0.451133,0

In [30]:
data.isna().sum()

age            0
sex            0
height         0
weight         0
qrsduration    0
              ..
channel_276    0
channel_277    0
channel_278    0
channel_279    0
target         0
Length: 279, dtype: int64

In [31]:
print(len(data.index))

420

In [38]:
len(data.columns)

279

In [32]:
data.to_csv('../data/arrhythmia/post_prep/arrhythmia.csv')

In [33]:
sm = SMOTE(random_state=42)
x, y = data.iloc[:, :-1], data.iloc[:, -1]
X_res, y_res = sm.fit_resample(x, y)

In [34]:
y_res

0      0
1      0
2      0
3      1
4      0
      ..
469    0
470    0
471    0
472    0
473    0
Name: target, Length: 474, dtype: int64

In [35]:
balanced_data = X_res
balanced_data["target"] = y_res

/var/folders/nx/ktkztyln3xn8f8j2qrfpjrlh0000gn/T/ipykernel_71388/1116103018.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  balanced_data["target"] = y_res

In [36]:
balanced_data.head()

,age,sex,height,weight,qrsduration,printerval,qtinterval,tinterval,pinterval,qrs,...,channel_271,channel_272,channel_273,channel_274,channel_275,channel_276,channel_277,channel_278,channel_279,target
0,1.0,0.0,0.125926,0.435294,0.270677,0.368321,0.501805,0.233333,0.590244,0.457478,...,1.000000,0.381356,0.968531,0.0,0.0,0.53125,0.741667,0.507519,0.569579,0
1,0.0,1.0,0.088889,0.341176,0.195489,0.332061,0.610108,0.140741,0.190244,0.577713,...,1.000000,0.360169,1.000000,0.0,0.0,0.31250,0.675000,0.485714,0.500971,0
2,0.0,0.0,0.099259,0.523529,0.624060,0.311069,0.555957,0.274074,0.497561,0.785924,...,1.000000,0.402542,0.916084,0.0,0.0,0.34375,0.783333,0.424812,0.566990,0
3,0.0,0.0,0.103704,0.517647,0.338346,0.385496,0.534296,0.251852,0.697561,0.586510,...,1.000000,0.516949,0.923077,0.0,0.0,0.37500,0.716667,0.592481,0.648544,1
4,1.0,0.0,0.094815,0.264706,0.338346,0.318702,0.321300,0.233333,0.443902,0.818182,...,0.853659,0.516949,0.902098,0.0,0.0,0.53125,0.683333,0.433835,0.451133,0

In [37]:
balanced_data.to_csv('../data/arrhythmia/post_prep/balanced_arrhythmia.csv')