In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from imblearn.over_sampling import SMOTE

In [2]:
data = pd.read_csv('../data/heart/heart.csv')

In [3]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [4]:
data = data.dropna()

In [5]:
data["sex"].value_counts()

sex
1    713
0    312
Name: count, dtype: int64

In [6]:
data['sex'] = data['sex'].map({1: 0, 0: 1}) # inverse

In [7]:
data["sex"].value_counts()

sex
0    713
1    312
Name: count, dtype: int64

In [8]:
len(data[(data['age'] >= 45) & (data['age'] <= 65)])

726

In [9]:
data['age'] = ((data['age'] < 45) | (data['age'] > 65)).astype(int) # not middle aged

In [10]:
len(data[data["age"] == 0].index)

726

In [11]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,0,0,0,125,212,0,1,168,0,1.0,2,2,3,0
1,0,0,0,140,203,1,0,155,1,3.1,0,0,3,0
2,1,0,0,145,174,0,1,125,1,2.6,0,0,3,0
3,0,0,0,148,203,0,1,161,0,0.0,2,1,3,0
4,0,1,0,138,294,1,1,106,0,1.9,1,3,2,0

In [12]:
scaler = MinMaxScaler()
scaler.fit(data[["trestbps"]])
data["trestbps"] = scaler.transform(data[["trestbps"]])

In [13]:
scaler = MinMaxScaler()
scaler.fit(data[["chol"]])
data["chol"] = scaler.transform(data[["chol"]])

In [14]:
scaler = MinMaxScaler()
scaler.fit(data[["thalach"]])
data["thalach"] = scaler.transform(data[["thalach"]])

In [15]:
scaler = MinMaxScaler()
scaler.fit(data[["oldpeak"]])
data["oldpeak"] = scaler.transform(data[["oldpeak"]])

In [16]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,0,0,0,0.292453,0.196347,0,1,0.740458,0,0.161290,2,2,3,0
1,0,0,0,0.433962,0.175799,1,0,0.641221,1,0.500000,0,0,3,0
2,1,0,0,0.481132,0.109589,0,1,0.412214,1,0.419355,0,0,3,0
3,0,0,0,0.509434,0.175799,0,1,0.687023,0,0.000000,2,1,3,0
4,0,1,0,0.415094,0.383562,1,1,0.267176,0,0.306452,1,3,2,0

In [17]:
categorical_attr = ['cp', 'restecg', 'slope', 'ca', 'thal']

In [18]:
for attr in categorical_attr:
    column_idx = data.columns.get_loc(attr)
    data = pd.concat([data, pd.get_dummies(data[attr], prefix=attr, dtype=int)], axis=1)

In [19]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,...,slope_2,ca_0,ca_1,ca_2,ca_3,ca_4,thal_0,thal_1,thal_2,thal_3
0,0,0,0,0.292453,0.196347,0,1,0.740458,0,0.161290,...,1,0,0,1,0,0,0,0,0,1
1,0,0,0,0.433962,0.175799,1,0,0.641221,1,0.500000,...,0,1,0,0,0,0,0,0,0,1
2,1,0,0,0.481132,0.109589,0,1,0.412214,1,0.419355,...,0,1,0,0,0,0,0,0,0,1
3,0,0,0,0.509434,0.175799,0,1,0.687023,0,0.000000,...,1,0,1,0,0,0,0,0,0,1
4,0,1,0,0.415094,0.383562,1,1,0.267176,0,0.306452,...,0,0,0,0,1,0,0,0,1,0

In [20]:
columns_order = [
    "age",
    "sex",
    "fbs",
    "restecg",
    "exang",
    "trestbps",
    "chol",
    "thalach",
    "oldpeak",
    "cp_0",
    "cp_1",
    "cp_2",
    "cp_3",
    "slope_0",
    "slope_1",
    "slope_2",
    "ca_0",
    "ca_1",
    "ca_2",
    "ca_3",
    "ca_4",
    "thal_0",
    "thal_1",
    "thal_2",
    "thal_3",
    "target",
]

In [21]:
len(columns_order)

26

In [22]:
data = data[columns_order]
data.head()

,age,sex,fbs,restecg,exang,trestbps,chol,thalach,oldpeak,cp_0,...,ca_0,ca_1,ca_2,ca_3,ca_4,thal_0,thal_1,thal_2,thal_3,target
0,0,0,0,1,0,0.292453,0.196347,0.740458,0.161290,1,...,0,0,1,0,0,0,0,0,1,0
1,0,0,1,0,1,0.433962,0.175799,0.641221,0.500000,1,...,1,0,0,0,0,0,0,0,1,0
2,1,0,0,1,1,0.481132,0.109589,0.412214,0.419355,1,...,1,0,0,0,0,0,0,0,1,0
3,0,0,0,1,0,0.509434,0.175799,0.687023,0.000000,1,...,0,1,0,0,0,0,0,0,1,0
4,0,1,1,1,0,0.415094,0.383562,0.267176,0.306452,1,...,0,0,0,1,0,0,0,1,0,0

In [23]:
print(len(data.index))

1025

In [24]:
data["target"].value_counts()

target
1    526
0    499
Name: count, dtype: int64

In [25]:
data.to_csv('../data/heart/post_prep/heart.csv')

In [26]:
# sm = SMOTE(random_state=42)
# x = data.drop(data.columns[1], axis=1)
# y = data.iloc[:, 1]
# X_res, y_res = sm.fit_resample(x, y)

In [27]:
sm = SMOTE(random_state=42)
x, y = data.iloc[:, :-1], data.iloc[:, -1]
X_res, y_res = sm.fit_resample(x, y)

In [28]:
y_res

0       0
1       0
2       0
3       0
4       0
       ..
1047    0
1048    0
1049    0
1050    0
1051    0
Name: target, Length: 1052, dtype: int64

In [29]:
# balanced_data = X_res
# balanced_data["sex"] = y_res

In [30]:
balanced_data = X_res
balanced_data["target"] = y_res

In [31]:
balanced_data = balanced_data[columns_order]

In [32]:
balanced_data.head()

,age,sex,fbs,restecg,exang,trestbps,chol,thalach,oldpeak,cp_0,...,ca_0,ca_1,ca_2,ca_3,ca_4,thal_0,thal_1,thal_2,thal_3,target
0,0,0,0,1,0,0.292453,0.196347,0.740458,0.161290,1,...,0,0,1,0,0,0,0,0,1,0
1,0,0,1,0,1,0.433962,0.175799,0.641221,0.500000,1,...,1,0,0,0,0,0,0,0,1,0
2,1,0,0,1,1,0.481132,0.109589,0.412214,0.419355,1,...,1,0,0,0,0,0,0,0,1,0
3,0,0,0,1,0,0.509434,0.175799,0.687023,0.000000,1,...,0,1,0,0,0,0,0,0,1,0
4,0,1,1,1,0,0.415094,0.383562,0.267176,0.306452,1,...,0,0,0,1,0,0,0,1,0,0

In [33]:
balanced_data["sex"].value_counts()

sex
0    737
1    315
Name: count, dtype: int64

In [34]:
balanced_data.to_csv('../data/heart/post_prep/balanced_heart.csv')