In [1]:
import pandas as pd
from sklearn.preprocessing import Binarizer
from imblearn.over_sampling import SMOTE

In [2]:
data = pd.read_csv('../data/stroke/stroke.csv')

In [3]:
data.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [4]:
data = data.dropna()

In [5]:
data = data.drop("id", axis="columns")

In [6]:
data = data[data['gender'] != 'Other']

In [7]:
data["gender"].value_counts()

gender
Female    2897
Male      2011
Name: count, dtype: int64

In [8]:
data['gender'] = pd.get_dummies(data['gender'], dtype=int)['Female']

In [9]:
data["gender"].value_counts()

gender
1    2897
0    2011
Name: count, dtype: int64

In [10]:
len(data[data["age"] >= 60].index)

1285

In [11]:
binarizer = Binarizer(threshold=59)
data['age'] = binarizer.fit_transform(data[['age']])

In [12]:
len(data[data["age"] == 1].index)

1285

In [13]:
data["ever_married"].value_counts()

ever_married
Yes    3204
No     1704
Name: count, dtype: int64

In [14]:
data['ever_married'] = pd.get_dummies(data['ever_married'], dtype=int)['Yes']

In [15]:
data["ever_married"].value_counts()

ever_married
1    3204
0    1704
Name: count, dtype: int64

In [16]:
data["Residence_type"].value_counts()

Residence_type
Urban    2490
Rural    2418
Name: count, dtype: int64

In [17]:
data['Residence_type'] = pd.get_dummies(data['Residence_type'], dtype=int)['Urban']

In [18]:
data["Residence_type"].value_counts()

Residence_type
1    2490
0    2418
Name: count, dtype: int64

In [19]:
categorical_attr = ['work_type', 'smoking_status']

In [20]:
for attr in categorical_attr:
    column_idx = data.columns.get_loc(attr)
    data = pd.concat([data, pd.get_dummies(data[attr], prefix=attr, dtype=int)], axis=1)

In [21]:
data = data.drop(labels=categorical_attr, axis=1)

In [22]:
data.head()

,gender,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,stroke,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,0,1.0,0,1,1,1,228.69,36.6,1,0,0,1,0,0,0,1,0,0
2,0,1.0,0,1,1,0,105.92,32.5,1,0,0,1,0,0,0,0,1,0
3,1,0.0,0,0,1,1,171.23,34.4,1,0,0,1,0,0,0,0,0,1
4,1,1.0,1,0,1,0,174.12,24.0,1,0,0,0,1,0,0,0,1,0
5,0,1.0,0,0,1,1,186.21,29.0,1,0,0,1,0,0,0,1,0,0

In [23]:
columns_order = [
    "gender",
    "age",
    "hypertension",
    "heart_disease",
    "ever_married",
    "Residence_type",
    "work_type_Govt_job",
    "work_type_Never_worked",
    "work_type_Private",
    "work_type_Self-employed",
    "work_type_children",
    "smoking_status_Unknown",
    "smoking_status_formerly smoked",
    "smoking_status_never smoked",
    "smoking_status_smokes",
    "avg_glucose_level",
    "bmi",
    "stroke"
]

In [24]:
len(columns_order)

18

In [25]:
data = data[columns_order]
data.head()

,gender,age,hypertension,heart_disease,ever_married,Residence_type,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,avg_glucose_level,bmi,stroke
0,0,1.0,0,1,1,1,0,0,1,0,0,0,1,0,0,228.69,36.6,1
2,0,1.0,0,1,1,0,0,0,1,0,0,0,0,1,0,105.92,32.5,1
3,1,0.0,0,0,1,1,0,0,1,0,0,0,0,0,1,171.23,34.4,1
4,1,1.0,1,0,1,0,0,0,0,1,0,0,0,1,0,174.12,24.0,1
5,0,1.0,0,0,1,1,0,0,1,0,0,0,1,0,0,186.21,29.0,1

In [26]:
print(len(data.index))

4908

In [27]:
data.to_csv('../data/stroke/post_prep/stroke.csv')

In [28]:
sm = SMOTE(random_state=42)
x, y = data.iloc[:, :-1], data.iloc[:, -1]
X_res, y_res = sm.fit_resample(x, y)

In [29]:
y_res

0       1
1       1
2       1
3       1
4       1
       ..
9393    1
9394    1
9395    1
9396    1
9397    1
Name: stroke, Length: 9398, dtype: int64

In [30]:
balanced_data = X_res
balanced_data["stroke"] = y_res

In [31]:
balanced_data.head()

,gender,age,hypertension,heart_disease,ever_married,Residence_type,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,avg_glucose_level,bmi,stroke
0,0,1.0,0,1,1,1,0,0,1,0,0,0,1,0,0,228.69,36.6,1
1,0,1.0,0,1,1,0,0,0,1,0,0,0,0,1,0,105.92,32.5,1
2,1,0.0,0,0,1,1,0,0,1,0,0,0,0,0,1,171.23,34.4,1
3,1,1.0,1,0,1,0,0,0,0,1,0,0,0,1,0,174.12,24.0,1
4,0,1.0,0,0,1,1,0,0,1,0,0,0,1,0,0,186.21,29.0,1

In [32]:
balanced_data.to_csv('../data/stroke/post_prep/balanced_stroke.csv')